import Anthropic from '@anthropic-ai/sdk'

export const hasApiKey = () => {
  return !!localStorage.getItem('claude_api_key')
}

export const generateContractWithClaude = async (contractType, formData) => {
  const apiKey = localStorage.getItem('claude_api_key')
  
  if (!apiKey) {
    throw new Error('No API key found. Please add your Claude API key in Settings.')
  }

  const anthropic = new Anthropic({
    apiKey: apiKey,
    dangerouslyAllowBrowser: true // Required for client-side usage
  })

  const prompt = buildPrompt(contractType, formData)

  try {
    const message = await anthropic.messages.create({
      model: 'claude-3-5-sonnet-20241022',
      max_tokens: 4096,
      messages: [{
        role: 'user',
        content: prompt
      }]
    })

    return message.content[0].text
  } catch (error) {
    if (error.status === 401) {
      throw new Error('Invalid API key. Please check your Claude API key in Settings.')
    } else if (error.status === 429) {
      throw new Error('Rate limit exceeded. Please try again in a moment.')
    } else {
      throw new Error(`API Error: ${error.message}`)
    }
  }
}

const buildPrompt = (contractType, formData) => {
  const basePrompt = `You are a legal contract expert specializing in entertainment industry agreements. Generate a professional, fair, and legally sound contract based on the following details.

IMPORTANT GUIDELINES:
- Use clear, professional legal language
- Include all standard clauses for this contract type
- Make it balanced and fair to both parties
- Include appropriate disclaimers
- Format it as a ready-to-sign document
- Add a footer note: "Generated by Entertainment Contracts AI - This is a sample contract. Consult a licensed attorney before signing."

`

  const prompts = {
    management: `
CONTRACT TYPE: Artist Management Agreement

DETAILS PROVIDED:
- Artist Name: ${formData.artistName || '[Not Provided]'}
- Manager Name: ${formData.managerName || '[Not Provided]'}
- Commission Rate: ${formData.commission || '15'}%
- Term Length: ${formData.term || '2 years'}
- Territory: ${formData.territory || 'Worldwide'}
- Notice Period: ${formData.noticePeriod || '30 days'}

Generate a complete Artist Management Agreement including:
1. Parties and engagement terms
2. Commission structure and payment terms
3. Manager's responsibilities and duties
4. Artist's obligations
5. Territory and exclusivity
6. Term and termination clauses
7. Dispute resolution
8. Additional standard clauses (assignment, governing law, etc.)
`,

    'split-sheet': `
CONTRACT TYPE: Split Sheet / Songwriting Agreement

DETAILS PROVIDED:
- Song Title: ${formData.songTitle || '[Not Provided]'}
- Writers: ${formData.writers || '[Not Provided]'}
- Ownership Splits: ${formData.splits || '[Not Provided]'}

Generate a complete Split Sheet including:
1. Song identification and date
2. All writers with ownership percentages
3. Publishing shares
4. PRO registration requirements
5. Copyright ownership
6. Income distribution terms
7. Credit requirements
8. Signature lines for all parties
`,

    nda: `
CONTRACT TYPE: Non-Disclosure Agreement (NDA)

DETAILS PROVIDED:
- Disclosing Party: ${formData.party1 || '[Not Provided]'}
- Receiving Party: ${formData.party2 || '[Not Provided]'}
- Purpose: ${formData.purpose || 'Business collaboration'}
- Term: ${formData.ndaTerm || '2 years'}

Generate a complete NDA including:
1. Definition of confidential information
2. Obligations of receiving party
3. Permitted uses and exceptions
4. Term and duration
5. Return of materials clause
6. Remedies for breach
7. Governing law and jurisdiction
`,

    distribution: `
CONTRACT TYPE: Music Distribution Agreement

DETAILS PROVIDED:
- Artist/Label: ${formData.artistName || '[Not Provided]'}
- Distributor: ${formData.distributorName || '[Not Provided]'}
- Territory: ${formData.territory || 'Worldwide'}
- Term: ${formData.term || '2 years'}
- Revenue Split: ${formData.split || 'Artist 70% / Distributor 30%'}

Generate a complete Distribution Agreement including:
1. Grant of rights and territory
2. Revenue splits and payment terms
3. Distributor obligations
4. Artist warranties and obligations
5. Accounting and reporting
6. Term and termination
7. Reversion of rights
`,

    producer: `
CONTRACT TYPE: Producer Agreement

DETAILS PROVIDED:
- Producer: ${formData.producerName || '[Not Provided]'}
- Artist: ${formData.artistName || '[Not Provided]'}
- Track/Project: ${formData.trackName || '[Not Provided]'}
- Fee: ${formData.fee || '[Not Provided]'}
- Points/Royalty: ${formData.points || '3% of net'}
- Master Ownership: ${formData.ownership || 'Artist owns masters'}

Generate a complete Producer Agreement including:
1. Services and deliverables
2. Compensation (upfront fee + points)
3. Credit requirements
4. Master recording ownership
5. Producer warranties
6. Sample clearance responsibilities
7. Publishing split (if applicable)
`,

    publishing: `
CONTRACT TYPE: Music Publishing Agreement

DETAILS PROVIDED:
- Songwriter: ${formData.songwriterName || '[Not Provided]'}
- Publisher: ${formData.publisherName || '[Not Provided]'}
- Term: ${formData.term || '3 years'}
- Advance: ${formData.advance || '[Not Provided]'}
- Publishing Split: ${formData.split || 'Publisher 50% / Writer 50%'}
- Territory: ${formData.territory || 'Worldwide'}

Generate a complete Publishing Agreement including:
1. Grant of rights
2. Advance and recoupment terms
3. Royalty splits (mechanical, performance, sync)
4. Minimum delivery requirements
5. Reversion clauses
6. Accounting and statements
7. Copyright ownership and administration
`,
  }

  return basePrompt + (prompts[contractType] || 'Generate a professional contract based on the provided information.')
}
