import { useState } from 'react'
import './App.css'

const contractTypes = [
  { id: 'management', name: '🎤 Artist Management Agreement', desc: 'Manager-artist relationship, commission rates, term length' },
  { id: 'distribution', name: '🎵 Distribution Deal', desc: 'Music distribution rights, royalty splits, territory' },
  { id: 'producer', name: '🎛️ Producer Agreement', desc: 'Beat/production rights, credits, payments' },
  { id: 'split-sheet', name: '💰 Split Sheet', desc: 'Songwriting credits and royalty percentages' },
  { id: 'nda', name: '🔒 NDA', desc: 'Confidentiality for collaborations and business deals' },
  { id: 'publishing', name: '📄 Publishing Agreement', desc: 'Publishing rights, advance, recoupment terms' },
]

function App() {
  const [selectedContract, setSelectedContract] = useState(null)
  const [formData, setFormData] = useState({})
  const [generatedContract, setGeneratedContract] = useState(null)
  const [loading, setLoading] = useState(false)

  const generateContract = () => {
    setLoading(true)
    // Simulate AI generation (in real app, this calls Claude API)
    setTimeout(() => {
      const contract = generateSampleContract(selectedContract, formData)
      setGeneratedContract(contract)
      setLoading(false)
    }, 2000)
  }

  const generateSampleContract = (type, data) => {
    const templates = {
      management: `ARTIST MANAGEMENT AGREEMENT

This Agreement is entered into on ${new Date().toLocaleDateString()} between:

ARTIST: ${data.artistName || '[Artist Name]'}
MANAGER: ${data.managerName || '[Manager Name]'}

1. ENGAGEMENT
Artist hereby engages Manager as Artist's sole and exclusive personal manager for a period of ${data.term || '2'} years.

2. COMMISSION
Manager shall receive ${data.commission || '15'}% of Artist's gross income from all entertainment-related activities.

3. TERRITORY
This agreement covers: ${data.territory || 'Worldwide'}

4. MANAGER RESPONSIBILITIES
- Advise Artist on career decisions
- Negotiate contracts on Artist's behalf  
- Coordinate with booking agents, labels, and other industry professionals
- Develop and execute career strategy

5. TERMINATION
Either party may terminate with ${data.noticePeriod || '30'} days written notice.

Generated by Entertainment Contracts AI - Not legal advice. Review with attorney before signing.`,
      
      'split-sheet': `SPLIT SHEET AGREEMENT

Song Title: ${data.songTitle || '[Song Title]'}
Date: ${new Date().toLocaleDateString()}

SONGWRITERS & SPLITS:

${data.writers ? data.writers.split(',').map((w, i) => `${i + 1}. ${w.trim()}: ${data.splits?.split(',')[i] || '25'}%`).join('\n') : '1. Writer 1: 50%\n2. Writer 2: 50%'}

PUBLISHING SHARES:
${data.writers ? data.writers.split(',').map((w, i) => `${i + 1}. ${w.trim()}: ${data.splits?.split(',')[i] || '25'}%`).join('\n') : '1. Writer 1: 50%\n2. Writer 2: 50%'}

All parties agree to register this work with their respective PROs (ASCAP/BMI/SESAC).

Generated by Entertainment Contracts AI - Not legal advice. Review with attorney before signing.`,

      nda: `NON-DISCLOSURE AGREEMENT

Date: ${new Date().toLocaleDateString()}

PARTIES:
Disclosing Party: ${data.party1 || '[Party 1]'}
Receiving Party: ${data.party2 || '[Party 2]'}

1. CONFIDENTIAL INFORMATION
All information shared regarding: ${data.purpose || 'musical collaboration, business opportunity'}

2. OBLIGATIONS
Receiving Party agrees to:
- Keep all information strictly confidential
- Not disclose to third parties without written consent
- Use information only for the stated purpose

3. TERM
This NDA remains in effect for ${data.ndaTerm || '2'} years from the date of signing.

4. EXCLUSIONS
Does not apply to information that is:
- Already publicly known
- Independently developed
- Required by law to be disclosed

Generated by Entertainment Contracts AI - Not legal advice. Review with attorney before signing.`,
    }

    return templates[type] || 'Contract template not found.'
  }

  const renderForm = () => {
    const forms = {
      management: (
        <>
          <input type="text" placeholder="Artist Name" onChange={(e) => setFormData({...formData, artistName: e.target.value})} />
          <input type="text" placeholder="Manager Name" onChange={(e) => setFormData({...formData, managerName: e.target.value})} />
          <input type="number" placeholder="Commission %" onChange={(e) => setFormData({...formData, commission: e.target.value})} />
          <input type="text" placeholder="Term (e.g., 2 years)" onChange={(e) => setFormData({...formData, term: e.target.value})} />
          <input type="text" placeholder="Territory (e.g., Worldwide)" onChange={(e) => setFormData({...formData, territory: e.target.value})} />
        </>
      ),
      'split-sheet': (
        <>
          <input type="text" placeholder="Song Title" onChange={(e) => setFormData({...formData, songTitle: e.target.value})} />
          <input type="text" placeholder="Writers (comma separated)" onChange={(e) => setFormData({...formData, writers: e.target.value})} />
          <input type="text" placeholder="Splits % (comma separated, must total 100%)" onChange={(e) => setFormData({...formData, splits: e.target.value})} />
        </>
      ),
      nda: (
        <>
          <input type="text" placeholder="Party 1 Name" onChange={(e) => setFormData({...formData, party1: e.target.value})} />
          <input type="text" placeholder="Party 2 Name" onChange={(e) => setFormData({...formData, party2: e.target.value})} />
          <input type="text" placeholder="Purpose (e.g., music collaboration)" onChange={(e) => setFormData({...formData, purpose: e.target.value})} />
          <input type="text" placeholder="Term (e.g., 2 years)" onChange={(e) => setFormData({...formData, ndaTerm: e.target.value})} />
        </>
      ),
    }

    return forms[selectedContract] || <p>Form coming soon for this contract type.</p>
  }

  if (generatedContract) {
    return (
      <div className="app">
        <div className="container">
          <button onClick={() => { setGeneratedContract(null); setSelectedContract(null); setFormData({}) }} className="back-btn">
            ← Back
          </button>
          <h2>Generated Contract</h2>
          <div className="contract-output">
            <pre>{generatedContract}</pre>
          </div>
          <div className="actions">
            <button onClick={() => navigator.clipboard.writeText(generatedContract)} className="btn-secondary">
              📋 Copy to Clipboard
            </button>
            <button onClick={() => {
              const blob = new Blob([generatedContract], { type: 'text/plain' })
              const url = URL.createObjectURL(blob)
              const a = document.createElement('a')
              a.href = url
              a.download = `${selectedContract}-contract.txt`
              a.click()
            }} className="btn-primary">
              💾 Download as TXT
            </button>
          </div>
          <p className="disclaimer">⚠️ This is a sample contract. Consult a licensed attorney before signing any legal document.</p>
        </div>
      </div>
    )
  }

  if (selectedContract) {
    return (
      <div className="app">
        <div className="container">
          <button onClick={() => setSelectedContract(null)} className="back-btn">← Back</button>
          <h2>{contractTypes.find(c => c.id === selectedContract)?.name}</h2>
          <p>{contractTypes.find(c => c.id === selectedContract)?.desc}</p>
          
          <div className="form">
            {renderForm()}
          </div>

          <button 
            onClick={generateContract} 
            className="btn-primary"
            disabled={loading}
          >
            {loading ? '⏳ Generating with AI...' : '✨ Generate Contract'}
          </button>
        </div>
      </div>
    )
  }

  return (
    <div className="app">
      <div className="hero">
        <h1>🎭 Entertainment Contracts AI</h1>
        <p className="tagline">Open-source legal contracts for independent artists</p>
        <p className="subtitle">Generate fair agreements without expensive lawyers. Powered by AI.</p>
      </div>

      <div className="container">
        <div className="stats">
          <div className="stat">
            <div className="stat-number">$0</div>
            <div className="stat-label">Cost</div>
          </div>
          <div className="stat">
            <div className="stat-number">2 min</div>
            <div className="stat-label">Generation Time</div>
          </div>
          <div className="stat">
            <div className="stat-number">6+</div>
            <div className="stat-label">Contract Types</div>
          </div>
        </div>

        <h2>Choose Contract Type</h2>
        <div className="contract-grid">
          {contractTypes.map(contract => (
            <div 
              key={contract.id} 
              className="contract-card"
              onClick={() => setSelectedContract(contract.id)}
            >
              <h3>{contract.name}</h3>
              <p>{contract.desc}</p>
            </div>
          ))}
        </div>

        <div className="cta-section">
          <h2>Why Use This?</h2>
          <div className="features">
            <div className="feature">
              <span className="feature-icon">⚖️</span>
              <h3>Fair & Balanced</h3>
              <p>Industry-standard terms that protect both parties</p>
            </div>
            <div className="feature">
              <span className="feature-icon">🤖</span>
              <h3>AI-Powered</h3>
              <p>Uses Claude AI to generate customized contracts</p>
            </div>
            <div className="feature">
              <span className="feature-icon">🌍</span>
              <h3>Open Source</h3>
              <p>Free forever. Community-driven improvements.</p>
            </div>
          </div>
        </div>

        <footer>
          <p>⚠️ Legal Disclaimer: This tool provides legal information, not legal advice. Contracts should be reviewed by a licensed attorney.</p>
          <p>Built with ❤️ for independent artists | <a href="https://github.com/EAJRD/entertainment-contracts-ai" target="_blank">GitHub</a></p>
        </footer>
      </div>
    </div>
  )
}

export default App
